# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 11:08
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('blurb', models.TextField(blank=True, max_length=150, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('header_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_header_image', to='filer.Image')),
                ('icon', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_icon_image', to='filer.Image')),
            ],
            options={
                'verbose_name': 'Project',
            },
        ),
    ]
