# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 12:53
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=colorfield.fields.ColorField(default=b'#FF0000', max_length=10),
        ),
    ]
