# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color_alpha',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
