# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_color_alpha'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_line',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
