# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 10:41
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_time_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10),
        ),
    ]
