# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170402_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('homepage_ordering',), 'verbose_name': 'Project'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.AddField(
            model_name='project',
            name='homepage_ordering',
            field=models.IntegerField(default=0),
        ),
    ]
