# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170402_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order',), 'verbose_name': 'Project'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='homepage_ordering',
            new_name='order',
        ),
    ]
