# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170402_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='font_color',
            field=models.CharField(choices=[('FW', 'White Font'), ('FB', 'Black Font')], default='FW', max_length=2),
        ),
    ]
