# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon_opacity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
