version: '2'

services:
    # PostgreSQL database
    db:
        image: postgres:9.6
        hostname: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"

    # Django web server
    web:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: web
        command: ./run_web.sh
        volumes:
            - .:/srv/www/sdupnz/sdupnz  # mount current directory inside container
        ports:
            - "8010:8010"
        # set up links so that web knows about db, rabbit and redis
        links:
            - db
        depends_on:
            - db

    # NGINX
    nginx:
        image: nginx:latest
        container_name: ng01
        ports:
            - "8000:8000"
        volumes:
            - .:/srv/www/sdupnz/sdupnz
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - web
