version: '2'

services:
    # PostgreSQL database
    db:
        restart: always
        image: postgres:9.6
        hostname: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5433:5432"

    # Memcache
    memcached:
        restart: always
        image: memcached
        hostname: memcached
        ports:
          - "11211:11211"


    # Django web server
    web:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        hostname: web
        command: ./run_web.sh
        volumes:
            - .:/srv/www/sdupnz/sdupnz  # mount current directory inside container
            - ./media:/srv/www/sdupnz/public-www/media
        ports:
            - "8009:8009"
        # set up links so that web knows about db, rabbit and redis
        links:
            - db
        depends_on:
            - db
