version: '2'

services:
    # PostgreSQL database
    db:
        restart: always
        image: postgres:9.6
        hostname: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5433:5432"
        networks:
            - back

    # Memcache
    memcached:
        restart: always
        image: memcached
        hostname: memcached
        ports:
            - "11211:11211"
        networks:
            - back


    # Django web server
    web:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        hostname: web
        environment:
            - VIRTUAL_HOST=sdup.nz
            - VIRTUAL_PORT=8009
        command: ./run_web.sh
        volumes:
            - .:/srv/www/sdupnz/sdupnz  # mount current directory inside container
            - ./media:/srv/www/sdupnz/public-www/media
        ports:
            - "8009:8009"
        # set up links so that web knows about db, rabbit and redis
        links:
            - db
        depends_on:
            - db
        networks:
            - reverse-proxy
            - back

networks:
    reverse-proxy:
        external:
            name: reverse-proxy
    back:
        driver: bridge
